### ISSUE TITLE
TypeError when use sample code in README.md

### ISSUE THREAD

**Issue by wudapeng268** [NTMC-Community/MatchZoo-py#106]
Thanks for your project. I install this package and run the code in ``README.md``, but I got the error. Following is the detail log:

```
Processing text_left with chain_transform of Tokenize => Lowercase => PuncRemoval: 100%|████████████████████████████████████████████████████████████████████████████████| 2118/2118 [00:00<00:00, 10964.68it/s]
Processing text_right with chain_transform of Tokenize => Lowercase => PuncRemoval: 100%|██████████████████████████████████████████████████████████████████████████████| 18841/18841 [00:03<00:00, 6015.32it/s]
Processing text_right with append:   0%|                                                                                                                                             | 0/18841 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test_matchzoo.py", line 15, in <module>
    train_processed = preprocessor.fit_transform(train_pack)
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/engine/base_preprocessor.py", line 97, in fit_transform
    return self.fit(data_pack, verbose=verbose) \
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/preprocessors/basic_preprocessor.py", line 110, in fit
    verbose=verbose)
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/preprocessors/build_unit_from_data_pack.py", line 32, in build_unit_from_data_pack
    data_pack.apply_on_text(corpus.append, mode=mode, verbose=verbose)
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/data_pack/data_pack.py", line 246, in wrapper
    func(target, *args, **kwargs)
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/data_pack/data_pack.py", line 401, in apply_on_text
    self._apply_on_text_right(func, rename, verbose=verbose)
  File "/public/anaconda3/lib/python3.7/site-packages/matchzoo_py-1.1-py3.7.egg/matchzoo/data_pack/data_pack.py", line 410, in _apply_on_text_right
    self._right[name] = self._right['text_right'].progress_apply(func)
  File "/public/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 730, in inner
    func = df._is_builtin_func(func)
  File "/public/anaconda3/lib/python3.7/site-packages/pandas/core/base.py", line 660, in _is_builtin_func
    return self._builtin_table.get(arg, arg)
TypeError: unhashable type: 'list'
Processing text_right with append:   0%|                                                                                                                                             | 0/18841 [00:00<?, ?it/s]

```
Matchzoo version is 1.1

**Comment by IsakZhang** [comment]
Hi @wudapeng268 , I wonder have u fixed it? I encounter the same problem. 
What's interesting is that the code runs well on my PC (Mac) but the issue appears when the code runs on Linux.

**Comment by wudapeng268** [comment]
Hi, @IsakZhang , I haven't fixed it. When I run the tutorials, I encounter the same problem. I tried both install method, but it doesn't work.

**Comment by Chriskuei** [comment]
It is caused by the latest version of tqdm (4.39). You can downgrad it by
```bash
pip install tqdm==4.38.0
```

**Comment by wudapeng268** [comment]
Thanks for your help. It works
