### ISSUE TITLE
cuDNN error when run sample code in README

### ISSUE THREAD

**Issue by wudapeng268** [NTMC-Community/MatchZoo-py#108]
Hi anyone,

I run the sample code in README, but got following error:

```
: block: [80,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [80,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
  0%|                                                                                                                                         | 0/32 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "test_matchzoo.py", line 62, in <module>
    trainer.run()
  File "/home/wup/MatchZoo-py/matchzoo/trainers/trainer.py", line 227, in run
    self._run_epoch()
  File "/home/wup/MatchZoo-py/matchzoo/trainers/trainer.py", line 252, in _run_epoch
    outputs = self._model(inputs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wup/MatchZoo-py/matchzoo/models/arci.py", line 187, in forward
    conv_left = self.conv_left(embed_left)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

My os is ubuntu 18.04
pytorch 1.3.1
cuda 10.0
cudnn 7.6.4

I can finely run another pytorch code at this server. Could you please help me?

**Comment by wudapeng268** [comment]
When running the code in CPU, I get following error:
```
Traceback (most recent call last):
  File "Test_readme.py", line 88, in <module>
    trainer.run()
  File "/home/wup/MatchZoo-py/matchzoo/trainers/trainer.py", line 227, in run
    self._run_epoch()
  File "/home/wup/MatchZoo-py/matchzoo/trainers/trainer.py", line 252, in _run_epoch
    outputs = self._model(inputs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wup/MatchZoo-py/matchzoo/models/arci.py", line 181, in forward
    embed_left = self.embedding(input_left.long()).transpose(1, 2)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/public/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 29748 out of table with 299 rows. at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

please let me know if I make any wrong. 

Thanks and Regards

**Comment by Chriskuei** [comment]
You should initialize an embedding for the model, which we forgot to add in README.
We have updated README, please check and retry. Sorry for the inconvenience.

**Comment by wudapeng268** [comment]
It works, thanks.
